apiVersion: v2
name: keycloak
version: 0.0.1-replace
appVersion: v17.0.0
description: Open Source Identity and Access Management For Modern Applications and Services
keywords:
  - sso
  - idm
  - openid connect
  - saml
  - kerberos
  - ldap
home: https://www.keycloak.org/
icon: https://www.keycloak.org/resources/images/keycloak_icon_512px.svg
sources:
  - https://github.com/codecentric/helm-charts
  - https://github.com/jboss-dockerfiles/keycloak
  - https://github.com/bitnami/charts/tree/master/bitnami/postgresql
maintainers:
  - name: doFlo Infrastructure Team
    email: infra@doflo.com
    url: https://infra.doflo.com
# dependencies:
#   - name: postgresql
#     version: 10.3.13
#     repository: https://charts.bitnami.com/bitnami
#     condition: postgresql.enabled
